import { AppData } from "../types";

export const AUTO_JSON_KEY = "dieta_e_peso_auto_json_backup";
export const MAIN_STORAGE_KEY = "projetoEmagrecimentoFinal";

export interface AutoBackupSnapshot {
  versaoBackup: string;
  dataExportacao: string;
  autoGenerated: boolean;
  appTitle: string;
  config: AppData["config"];
  registros: AppData["registros"];
  medicamentos: AppData["medicamentos"];
  musculacao: any[];
  cardio: any[];
  rastreadorSubcutaneo: {
    completedApplications: string[];
  };
  planoNutricional: any;
  controleAgua: {
    metaAguaMl: number | null;
    historicoAguaDiario: Record<string, number>;
  };
  segurancaAcesso: {
    acessoProjeto: any;
    acessoTemporario: any;
  };
}

/**
 * Generates a complete JSON backup object of all application data,
 * saves it to localStorage ("dieta_e_peso_auto_json_backup"), and returns the JSON string.
 */
export function salvarJsonSnapshotAuto(currentAppData: AppData): string {
  try {
    // 1. Rastreador Subcutâneo
    let subcutaneaCompleted: string[] = [];
    const savedInjections = localStorage.getItem("subcutanea_completed_applications");
    if (savedInjections) {
      try { subcutaneaCompleted = JSON.parse(savedInjections); } catch (e) { console.error(e); }
    }

    // 2. Plano Nutricional
    let planoNutricionalData: any = null;
    const savedPlano = localStorage.getItem("plano_nutricional_custom_v2");
    if (savedPlano) {
      try { planoNutricionalData = JSON.parse(savedPlano); } catch (e) { console.error(e); }
    }

    // 3. Atividade Física
    let musculacaoData: any[] = currentAppData.musculacao || [];
    let cardioData: any[] = currentAppData.cardio || [];
    const savedMusc = localStorage.getItem("atividade_musculacao_list");
    if (savedMusc) {
      try { musculacaoData = JSON.parse(savedMusc); } catch (e) { console.error(e); }
    }
    const savedCardio = localStorage.getItem("atividade_cardio_list");
    if (savedCardio) {
      try { cardioData = JSON.parse(savedCardio); } catch (e) { console.error(e); }
    }

    // 4. Controle de Água
    const metaAguaRaw = localStorage.getItem("meta_agua_ml");
    const metaAguaMl = metaAguaRaw ? parseInt(metaAguaRaw, 10) : null;
    const historicoAguaDiario: Record<string, number> = {};
    for (let i = 0; i < localStorage.length; i++) {
      const k = localStorage.key(i);
      if (k && k.startsWith("agua_consumida_")) {
        const val = localStorage.getItem(k);
        if (val) historicoAguaDiario[k] = parseInt(val, 10) || 0;
      }
    }

    // 5. Segurança / Tokens
    const acessoProjeto = localStorage.getItem("acesso_projeto");
    const acessoTemporario = localStorage.getItem("acesso_app_temporario");

    const snapshot: AutoBackupSnapshot = {
      versaoBackup: "2.0-auto",
      dataExportacao: new Date().toISOString(),
      autoGenerated: true,
      appTitle: "Projeto Emagrecimento & Dieta Pro",
      config: currentAppData.config,
      registros: currentAppData.registros || [],
      medicamentos: currentAppData.medicamentos || [],
      musculacao: musculacaoData,
      cardio: cardioData,
      rastreadorSubcutaneo: {
        completedApplications: subcutaneaCompleted
      },
      planoNutricional: planoNutricionalData,
      controleAgua: {
        metaAguaMl,
        historicoAguaDiario
      },
      segurancaAcesso: {
        acessoProjeto: acessoProjeto ? JSON.parse(acessoProjeto) : null,
        acessoTemporario: acessoTemporario ? JSON.parse(acessoTemporario) : null
      }
    };

    const jsonString = JSON.stringify(snapshot, null, 2);
    localStorage.setItem(AUTO_JSON_KEY, jsonString);
    localStorage.setItem(MAIN_STORAGE_KEY, JSON.stringify(currentAppData));
    return jsonString;
  } catch (err) {
    console.error("Erro ao gerar JSON auto snapshot:", err);
    return "";
  }
}

/**
 * Restores all application data from the stored auto JSON snapshot ("dieta_e_peso_auto_json_backup" or fallback).
 */
export function restaurarJsonSnapshotAuto(): { success: boolean; appData?: AppData; message?: string } {
  try {
    const rawJson = localStorage.getItem(AUTO_JSON_KEY) || localStorage.getItem(MAIN_STORAGE_KEY);
    if (!rawJson) {
      return { success: false, message: "Nenhum JSON de backup automático localizado." };
    }

    const parsed = JSON.parse(rawJson);
    if (!parsed || typeof parsed !== "object") {
      return { success: false, message: "JSON de backup corrompido ou inválido." };
    }

    // Extract AppData configuration & logs
    const config = {
      pesoInicial: parseFloat(parsed.config?.pesoInicial) || 80,
      metaPerda: parseFloat(parsed.config?.metaPerda) || 10,
      dataInicio: parsed.config?.dataInicio || "2026-06-01",
      foto: parsed.config?.foto || "",
      nome: parsed.config?.nome || "",
      sexo: parsed.config?.sexo || "",
      idade: parsed.config?.idade !== undefined ? Number(parsed.config.idade) : undefined,
    };
    const registros = Array.isArray(parsed.registros) ? parsed.registros : [];
    const medicamentos = Array.isArray(parsed.medicamentos) ? parsed.medicamentos : [];
    const musculacao = Array.isArray(parsed.musculacao) ? parsed.musculacao : [];
    const cardio = Array.isArray(parsed.cardio) ? parsed.cardio : [];

    const restoredAppData: AppData = {
      config,
      registros,
      medicamentos,
      musculacao,
      cardio
    };

    // Restore to localStorage subkeys
    localStorage.setItem(MAIN_STORAGE_KEY, JSON.stringify(restoredAppData));

    if (musculacao.length > 0) {
      localStorage.setItem("atividade_musculacao_list", JSON.stringify(musculacao));
    }
    if (cardio.length > 0) {
      localStorage.setItem("atividade_cardio_list", JSON.stringify(cardio));
    }
    if (parsed.rastreadorSubcutaneo?.completedApplications) {
      localStorage.setItem("subcutanea_completed_applications", JSON.stringify(parsed.rastreadorSubcutaneo.completedApplications));
    }
    if (parsed.planoNutricional) {
      localStorage.setItem("plano_nutricional_custom_v2", JSON.stringify(parsed.planoNutricional));
    }
    if (parsed.controleAgua) {
      if (parsed.controleAgua.metaAguaMl) {
        localStorage.setItem("meta_agua_ml", parsed.controleAgua.metaAguaMl.toString());
      }
      if (parsed.controleAgua.historicoAguaDiario) {
        Object.entries(parsed.controleAgua.historicoAguaDiario).forEach(([k, v]) => {
          if (v !== undefined && v !== null) {
            localStorage.setItem(k, String(v));
          }
        });
      }
    }

    return { success: true, appData: restoredAppData, message: "JSON buscado e dados restaurados com sucesso!" };
  } catch (err) {
    console.error("Erro ao restaurar JSON snapshot:", err);
    return { success: false, message: "Erro ao processar arquivo JSON." };
  }
}
